spring.application.name=smart-dormitory-backend
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/smart_dormitory
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.jwt.secret=dGhpcy1pcy1hLXNlY3JldC1mb3Itc21hcnQtZG9ybWl0b3J5LWFwcA==
app.jwt.expiration-ms=3600000

logging.level.org.springframework.security=INFO
